name: MSBuild
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1

    - run: nuget restore IE7RenderChecker.sln

    - name: Build
      run: msbuild IE7RenderChecker.sln /t:Rebuild /p:Configuration=Release /p:Platform='Any CPU'
    
    - name: zip
      run: Compress-Archive -DestinationPath IE7RenderChecker-${{ github.sha }}.zip -Path IE7RenderChecker/bin/Release/
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: IE7RenderChecker-${{ github.sha }}
        path: IE7RenderChecker-${{ github.sha }}.zip


